version: '3.8'
services:
  db:
    image: 'postgres:16.3'
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blogapi
      POSTGRES_USER: blogapi_user
      POSTGRES_PASSWORD: blogapi_pass
      POSTGRES_ROOT_PASSWORD: blogapi_root_pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
